//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SİNEMASEANSTAKİP
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzlvefkl
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> datetimee { get; set; }
        public string clock { get; set; }
    }
}
