//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SİNEMASEANSTAKİP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOVIETICKETSEntities1 : DbContext
    {
        public MOVIETICKETSEntities1()
            : base("name=MOVIETICKETSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<belle> belle { get; set; }
        public virtual DbSet<galaksi> galaksi { get; set; }
        public virtual DbSet<Mstrlr> Mstrlr { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
        public virtual DbSet<umut> umut { get; set; }
        public virtual DbSet<hzlvefkl> hzlvefkl { get; set; }
    }
}
